dusting

diff --git a/configs/shared b/configs/shared
--- a/configs/shared
+++ b/configs/shared
@@ -2,14 +2,15 @@
 # shellcheck disable=SC1090,SC2034
 
 center() {
-  width="$(tput cols)"
-  padding="$(printf '%0.1s' \ {1..500})"
-  printf '%*.*s %s %*.*s\n' 0 "$(((width-2-${#1})/2))" "$padding" "$1" 0 "$(((width-1-${#1})/2))" "$padding"
+    width="$(tput cols)"
+    padding="$(printf '%0.1s' \ {1..500})"
+    printf '%*.*s %s %*.*s\n' 0 "$(((width - 2 - ${#1}) / 2))" "$padding" "$1" 0 "$(((width - 1 - ${#1}) / 2))" "$padding"
 }
 
 title() {
     INPUT="${1//\"/}"
     center "$INPUT"
+    echo " "
 }
 
 logo() {
@@ -23,9 +24,9 @@ logo() {
     center "  .8'   '8. '88888.  8b   '8.'8888.  .8'   '8. '88888.    8 8888"
     center " .888888888. '88888. '8b.  ;8.'8888 .888888888. '88888.   8 8888"
     center ".8'       '8. '88888. 'Y8888P ,88P'.8'       '8. '88888.  8 8888"
-    echo ""   
+    echo -ne "\n"
     center "                Archlinux System Automated Installer            "
-    echo "" 
+    echo -ne "\n"
 }
 
 source_file() {
@@ -46,13 +47,12 @@ set_option() {
     echo "${1}=${2}" >>"$CONFIG_FILE"
 }
 
-install_pkg () {
-    pacman -S --noconfirm --needed "$@" >/dev/null 2>&1
+install_pkg() {
+    sudo pacman -S --noconfirm --needed "$@" >/dev/null 2>&1
 }
 
-something_failed() {
-    echo -ne "ERROR! Something is not right. Exiting.\n"
-    exit 0
+install_aur() {
+    "$AURHELPER" -S --noconfirm --needed "$@" /dev/null 2>&1
 }
 
 invalid_option() {
@@ -95,6 +95,10 @@ connection_test() {
     ping -q -w 1 -c 1 "$(ip r | grep default | awk 'NR==1 {print $3}')" &>/dev/null && return 1 || return 0
 }
 
+mount_check() {
+    [[ "$(grep -E "$MOUNTPOINT" /proc/mounts -c)" -ne 0 ]] && return 1 || return 0
+}
+
 elements_present() {
     for e in "${@:2}"; do [[ "$e" == "$1" ]] && break; done
 }
@@ -109,7 +113,7 @@ set_ntp() {
     timedatectl set-ntp true
 }
 
-background_checks(){
+background_checks() {
     root_check
     docker_check
     arch_check
@@ -117,16 +121,19 @@ background_checks(){
     if connection_test; then
         echo -ne "ERROR! There seems to be no internet connection.\n"
         exit 0
+    elif mount_check; then
+        echo -ne "ERROR! The mountpoint is already in use.\n"
+        exit 0
     fi
     set_ntp
 }
 
 copy_logs() {
     echo "Copying logs"
-    cp -v "$LOG" "$MOUNTPOINT"/var/log/asai.log
+    cp -v "$LOG_FILE" "$MOUNTPOINT"/var/log/asai.log
 }
 
-do_reboot() {
+do_exit() {
     echo "unmounting $MOUNTPOINT"
     if [[ "$LVM" -eq "1" || "$LUKS" -eq "1" ]]; then
         i=0
@@ -136,38 +143,21 @@ do_reboot() {
     fi
     umount -R "$MOUNTPOINT"/boot
     umount -R "$MOUNTPOINT"
-    echo "Rebooting..."
-    reboot
 }
 
 end() {
-    REBOOT="true"
     copy_logs
-    for ((i = 15; i >= 1; i--)); do
-        read -r -s -n 1 -t 1 -p "ASAI is rebooting in $i seconds... Press Esc key to abort or press R key to reboot now."$'\n' KEY
-        CODE="$?"
-        if [ "$CODE" != "0" ]; then
-            continue
-        fi
-        if [[ "$KEY" == $'\e' ]]; then
-            REBOOT="false"
-            break
-        elif [[ "$KEY" == "r" || "$KEY" == "R" ]]; then
-            REBOOT="true"
-            break
-        fi
-    done
-    if [[ "$REBOOT" == "true" ]]; then
-        do_reboot
-    else
-        echo "Reboot is aborted "
-    fi
+    do_exit
 }
 
-pacman -Sy --noconfirm
-install_pkg terminus-font
+start_jobs() {
+    echo "Refreshing pacman database"
+    pacman -Sy --noconfirm >/dev/null 2>&1
+    echo "Installing fonts"
+    install_pkg terminus-font
 
-fc-cache -fv >/dev/null 2>&1
-setfont ter-v22b
-
+    fc-cache -fv >/dev/null 2>&1
+    echo "Setting up fonts"
+    setfont ter-v22b
+}
 _TIMEZONE="$(curl --fail https://ipapi.co/timezone)"
diff --git a/scripts/0-preinstall b/scripts/0-preinstall
--- a/scripts/0-preinstall
+++ b/scripts/0-preinstall
@@ -1,7 +1,5 @@
 #!/usr/bin/env bash
 
-# shellcheck disable=SC2001
-
 make_boot() {
     if [[ "$UEFI" -eq 1 ]]; then
         mkfs.vfat -F32 -n "$BOOT" "$PART1"
@@ -75,7 +73,8 @@ do_format() {
         mkfs.ntfs -Q -L "$ROOT" "$1"
         ;;
     *)
-        something_failed
+        echo "ERROR! Unsupported filesystem"
+        exit 0
         ;;
     esac
 
@@ -138,7 +137,7 @@ mount_boot() {
 
 logo
 title "Preinstall setup"
-echo "Setting up mirrors for faster downloads"
+echo "installing reflector rsync"
 install_pkg pacman-contrib reflector rsync gptfdisk
 
 sed -i 's/^#ParallelDownloads/ParallelDownloads/' /etc/pacman.conf
@@ -146,8 +145,8 @@ sed -i 's/^#ParallelDownloads/ParallelDownloads/' /etc/pacman.conf
 if [[ ! -f /etc/pacman.d/mirrorlist.backup ]]; then
     cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
 fi
-
-reflector --age 48 --country "$ISO" -f 5 --latest 20 --protocol https --sort rate --save /etc/pacman.d/mirrorlist
+echo "Generating new mirrorlist"
+reflector --age 48 --country "$ISO" -f 5 --latest 20 --protocol https --sort rate --save /etc/pacman.d/mirrorlist >/dev/null 2>&1
 mkdir "$MOUNTPOINT" &>/dev/null
 
 echo "File system setup"
@@ -162,14 +161,14 @@ fi
 set_option "PART2" "$PART2"
 
 case "$LAYOUT" in
-btrfs)
+"btrfs")
     do_partition
     make_boot
     do_btrfs "$ROOT" "$PART2"
     mount_boot
     ;;
 
-lvm)
+"lvm")
     PACKAGES+=("lvm2")
     do_partition
     sgdisk --typecode=2:8e00 "$DISK"
@@ -183,7 +182,7 @@ lvm)
     set_option "HOOKS" "(lvm2 filesystems)"
     ;;
 
-luks)
+"luks")
     PACKAGES+=("cryptsetup" "lvm2")
     do_partition
     make_boot
@@ -198,7 +197,7 @@ luks)
     set_option "HOOKS" "(base udev autodetect keyboard keymap consolefont modconf block lvm2 encrypt filesystems fsck)"
     ;;
 
-none)
+"none")
     modprobe dm-mod
     vgscan &>/dev/null
     vgchange -ay &>/dev/null
@@ -211,29 +210,27 @@ none)
     ;;
 
 *)
-    something_failed
+    echo "ERROR! Unsupported Partition layout"
+    exit 0
     ;;
 esac
 
-if [[ "$(grep -E "$MOUNTPOINT" /proc/mounts -c)" -eq "0" ]]; then
-    echo "Drive is not mounted can not continue"
-    echo "Rebooting in 3 Seconds ..." && sleep 1
-    echo "Rebooting in 2 Seconds ..." && sleep 1
-    echo "Rebooting in 1 Second ..." && sleep 1
+if ! mount_check; then
+    echo -ne "ERROR! The mountpoint is not in use.\n"
     exit 0
 fi
 
-echo "Arch Install on Main Drive"
-pacstrap "$MOUNTPOINT" base base-devel linux linux-firmware vim sudo archlinux-keyring wget libnewt "${PACKAGES[@]}" --noconfirm --needed
+echo "Starting pacstrap"
+pacstrap "$MOUNTPOINT" base base-devel linux linux-firmware vim sudo archlinux-keyring wget "${PACKAGES[@]}" --noconfirm --needed
+echo "Registering keyserver"
 echo "keyserver hkp://keyserver.ubuntu.com" >>"$MOUNTPOINT"/etc/pacman.d/gnupg/gpg.conf
 
 echo "Generating fstab"
 genfstab -U "$MOUNTPOINT" >>"$MOUNTPOINT"/etc/fstab
 
-cp -R "$SCRIPT_DIR" "$MOUNTPOINT"/root/ArchTitus
+cp -R "$SCRIPT_DIR" "$MOUNTPOINT"/root/asai
 cp /etc/pacman.d/mirrorlist "$MOUNTPOINT"/etc/pacman.d/mirrorlist
 
-TOTALMEM="$(grep -i "memtotal" "/proc/meminfo" | grep -o '[[:digit:]]*')"
 if [[ $TOTALMEM -lt 8000000 ]]; then
     echo "Checking for low memory systems "
     mkdir -p "$MOUNTPOINT"/opt/swap &>/dev/null
@@ -241,7 +238,7 @@ if [[ $TOTALMEM -lt 8000000 ]]; then
         chattr +C "$MOUNTPOINT"/opt/swap
     fi
     dd if=/dev/zero of="$MOUNTPOINT"/opt/swap/swapfile bs=1M count=2048 status=progress
-    chmod 600 "$MOUNTPOINT"/opt/swap/swapfile 
+    chmod 600 "$MOUNTPOINT"/opt/swap/swapfile
     chown root "$MOUNTPOINT"/opt/swap/swapfile
     mkswap "$MOUNTPOINT"/opt/swap/swapfile
     swapon "$MOUNTPOINT"/opt/swap/swapfile
